### ISSUE TITLE
avoid default virtualbox-addons

### ISSUE THREAD

**Issue by hyperknot** [kraksoft/vagrant-box#1]
You can avoid the default install with this in preseed. Source: https://github.com/jedi4ever/veewee/blob/master/templates/Debian-7.7.0-amd64-netboot/preseed.cfg#L306

```
# Prevent packaged version of VirtualBox Guest Additions being installed:
d-i preseed/early_command string sed -i \
  '/in-target/idiscover(){/sbin/discover|grep -v VirtualBox;}' \
  /usr/lib/pre-pkgsel.d/20install-hwpackages
```

**Comment by kedrap** [comment]
Thx for info.

But for me, it also looks like removing VirtualBox Guest Additions after all, as a last action in preseed.cfg. The only difference is, that in this case - it's done using preseed/early_command, and in my case - it's done using preseed/late_command.

But I still don't know why, when I install only this packages [build-essential ca-certificates curl nfs-common ssh](https://github.com/kraksoft/vagrant-box/blob/master/debian/preseed.cfg#L56) virtualbox-\* packages are already preinstalled?

**Comment by hyperknot** [comment]
preseed/early_command runs before anything else, and it avoids the automatic installation of the packages. Try it, it's exactly what you are looking for based on the comment.

**Comment by kedrap** [comment]
I still couldn't figure it out, why all those VirtualBox stuff was installed, while it wasn't on any 'package list'.
But now, I have had a little more time, and I have read about it.

I have found, that it's installed because it's discovered by /sbin/discover command.
And now, everything looks clearer for me :)

Once again, thanks for tip.
I have also released a new versions.
